services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Shopsys\CategoryFeed\LuigisBoxBundle\:
        resource: '../../*'

    Shopsys\CategoryFeed\LuigisBoxBundle\LuigisBoxCategoryFeed:
        tags:
            - { name: shopsys.feed, hours: '*', minutes: '5' }
